platform :ios, '10.0'
use_frameworks!

target ‘view-nav’ do
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'Alamofire','~>4.0'
    pod 'SDWebImage', '~>3.8'
    pod 'SnapKit', '~> 3.0.2'
    pod 'SwiftyJSON’
    pod 'FontAwesome.swift'
end
